---
--- Generated by Luanalysis
--- Created by chaunsin.
--- DateTime: 2024/5/24 10:36
---

print("hello world")

local list = { { 'name', "age" }, { "sex", "address" } }
print(list) -- table: 0x6000020ec140
