version: '3.2'
services:
  nginx:
    image: nginx
    container_name: jcx_nginx
    restart: always
    depends_on:
      - jcx
    environment:
      - TZ=Asia/Shanghai
    networks:
      - jcx-network
    ports:
      - '80:80'
      - '8090:8090'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw # 挂载配置文件
      - ./nginx/conf.d:/etc/nginx/conf.d:rw # 挂载配置文件
      - ./nginx/html:/usr/share/nginx/html:ro # 挂载html
      - ./nginx/log:/var/log/nginx/:rw  # 挂载日志
  jcx:
    image: jcx-test:v0.0.0
    #    container_name: jcx_test # 指定容器名称.当指定名称时不能使用scale命令起动多个服务,因为容器名称是唯一的
    #    restart: "no"  # 默认方式,在任何情况下都不重启
    #    restart: on-failure:3 # 在容器非正常退出时（退出状态非0）,才会重启容器. 3代表最多重启3次,如果不指定则无限重启
    #    restart: unless-stopped # 总是重启 除非容器停止(手动或其他方式)
    restart: always # 总是重启
    networks:
      - jcx-network
#    ports:
#      - '8080'
#      - '8080:8080'

# 创建网络 相当于命令:docker network create
networks:
  jcx-network:
#    external: true  # 使用预先存在的网络