version: '3.2'
services:
  ngnix:
    image: nginx
    container_name: nginx
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw # 挂载配置文件
      - ./nginx/conf.d:/etc/nginx/conf.d:rw # 挂载配置文件
      - ./nginx/html:/usr/share/nginx/html:ro # 挂载html
      - ./nginx/log:/var/log/nginx/:rw  # 挂载日志