kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jcx-test
  namespace: public-service
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "nfs"
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs
